version: '3.4'

services:
  myname:
    container_name: svc_name
    # hostname: foo # optional, usually not needed
    image: "foo/bar"
    ports:
      - "2000:7080"
      - "3000:5050"
      - 8100/udp # expose only UDP on 8100
    environment:
      - TZ: 'America/Denver'
      # If support, mask internal user gid/uid to avoid permissions issues.
      - "PUID=1000"
      - "PGID=1000"
    labels: # traefik
      - "traefik.http.routers.foo.rule=Host(`foo.docker`, `foo.docker.smirnovlabs`)"
      - "traefik.http.services.foo.loadbalancer.server.port=123"
    volumes:
       - './data:/data'
       - '/some/file/path:/config'
    restart: unless-stopped # or 'always'
